[features]
seeds = false
skip-lint = false
[programs.localnet]
rent_nft = "FQ9MA87E8H8B3aGxnGQwmXNGzgRTap9WL9Yhk3GZT9w8"

# Token2022 Loader
[[test.validator.account]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
filename = "deps/token2022_loader.json"

[[test.validator.account]]
address = "DoU57AYuPFu2QU514RktNPG22QhApEjnKxnBcu4BHDTY"
filename = "deps/token2022_data.json"

[[test.genesis]]
address = "9msweUGitRR1ELUe4XZi6xhecPCko54kSqSnfWH7LLiZ"
program = "deps/nft_standard.so"

# [test.validator]
# url = "https://api.mainnet-beta.solana.com"
[test.validator]
url = "https://swr.xnfts.dev/rpc-proxy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
